### ISSUE TITLE
在doupan.go中89 if err != nil  是不是该是错误的？

### ISSUE THREAD

**Issue by Gooooodman** [tangdu/golang#1]
`if err != nil {
                fmt.Println("Start Down File Err....")
                log.Fatal(err)
            } else {
                //fmt.Println(root)
                crawMusic(root.Song, &sinfo)
                //log.Fatal(err)
            }`

**Comment by tangdu** [comment]
if err != nil {
                fmt.Println("Start Down File....")
                crawMusic(root.Song, &sinfo)
            } else {
                log.Fatal(err)
            }
没有错误才抓取 ，

**Comment by Gooooodman** [comment]
@tangdu err != nil  err说明不为nil就是有错误哦。怎么还抓取呢？？？？
